services:
    mak_survey.survey_repository:
        class: Mak\SurveyBundle\Repository\SurveyRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - Mak\SurveyBundle\Model\Survey
    mak_survey.page_repository:
        class: Mak\SurveyBundle\Repository\PageRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - Mak\SurveyBundle\Model\Page
